# Generated by Django 4.0.2 on 2022-02-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Nowy', 'Nowy'), ('Zakończony', 'Zakończony')], default='Nowy', max_length=30)),
            ],
        ),
    ]
