# Generated by Django 4.0.2 on 2022-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_start_date_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
