# Generated by Django 4.0.2 on 2022-02-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_comment_delete_commentsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='project_id',
        ),
    ]
